[workspace]
resolver = "2"
members = [
    ".",
    "crates/*"
]

[workspace.package]
edition = "2021"
authors = ["Yevhen Kazmin <gvoin16@gmail.com>"]
version = "0.1.0"

[workspace.dependencies]
tokio = { version = "1.28.1", features = ["full"] }
tracing = "0.1"
anyhow = "1.0"

[package]
name = "cg-arena"
edition.workspace = true
authors.workspace = true
version.workspace = true

[dependencies]
tokio.workspace = true
tracing.workspace = true
anyhow.workspace = true

tracing-subscriber = "0.3"
clap = { version = "4.2.7", features = ["derive"] }
colored = "2.0.4"
tempdir = "0.3.7"

server = { path = "crates/server" }