[game]
min_players = 2
max_players = 2
# Whether the map is symmetric for all the players. If set to false extra mirror matches would be played.
symmetric = true

[matchmaking]
allow_same_bots = false
min_matches = 200
min_matches_preference = 1.0

[ranking]
algorithm = "weng_lin"

[server]
port = 1234

[embedded_worker]
threads = 1
dir_bots = "bots"
cmd_play_match = "python play_game.py %P1% %P2%"

[[embedded_worker.languages]]
name = "cpp"
# assuming bot folder (%DIR%) contains source code in the "source.txt" file
cmd_build = "g++ -std=c++17 -x c++ %DIR%/source.txt -o %DIR%/a.exe"
cmd_run = "./%DIR%/a.exe"

[[embedded_worker.languages]]
name = "python"
cmd_build = "mv %DIR%/source.txt %DIR%/bot.py"
cmd_run = "python %DIR%/bot.py"

[[embedded_worker.languages]]
name = "rust"
cmd_build = "sh languages/rust/build.sh %DIR%"
cmd_run = "./%DIR%/a.exe"
