[game]
min_players = 2
max_players = 2
# Whether the map is symmetric for all the players. If set to false extra mirror matches would be played.
symmetric = true
# The command to start the referee process. The referee must output score for each player after the game ends.
referee_file = "cg-referee-ghost-in-cell.jar"
referee_cmd = "java -jar ${referee_file}"

[[languages]]