[game]
min_players = 2
max_players = 2
# Whether the map is symmetric for all the players. If set to false extra mirror matches would be played.
symmetric = true
# The command to start the referee process. The referee must output score for each player after the game ends.
referee_file = "cg-referee-ghost-in-cell.jar"
referee_cmd = "java -jar ${referee_file}"

[[languages]]
name = "C++"
file_extension = "cpp"
health_check_cmd = ["g++", "--version"]
build_cmd = ["g++", "--std=c++17", "-Og", "-o bot", "${source_file}"]
run_cmd = ["./bot"]

[server]
host = "127.0.0.1"
port = 12345
embedded_worker_threads = 1
